### ISSUE TITLE
System text gets cut off

### ISSUE THREAD

**Issue by DAOWAce** [Miei/TOS-lua#10]
Not sure why this is happening, just noticed it after updating to the most recent version (after text links were added; downloaded repo today too)

![classicchat cutoff](https://cloud.githubusercontent.com/assets/480587/15386067/b48f9a9e-1d73-11e6-8970-2421432229d1.png)

Some of the text in that example was cut off but showed itself again somehow.  Maybe it changed based on further text or area swaps; didn't take notice.

**Comment by TehSeph** [comment]
Formatting bug. I have the same issue with my colors addon.

**Comment by Miei** [comment]
I noticed this yesterday too, I'm going to look into it a bit today.

**Comment by Miei** [comment]
Should be fixed in latest version.

**Comment by DAOWAce** [comment]
Late, but thank you for the update.

Wanted to confirm it was working first, but I've put the game on hold until the lag and performance issues are sorted out, so I haven't been on at all.  Figured I've delayed enough!

Back to Dwarf Fortress..
