### ISSUE TITLE
ClassicChat transparency bug

### ISSUE THREAD

**Issue by Schmongo** [Miei/TOS-lua#16]
hey there!
small bug that i encountered:
the custom chat background doesn't activate automatically for anything but the "all" tab!
when you change the transparency manually it changes but doesn't persist through a restart of the game.

**Comment by Miei** [comment]
For me it works on any tab, can you screenshot this issue and give some more details about the situations that it applies in?

**Comment by Schmongo** [comment]
ok the issue only occurs when i start the game. everything but the "all" tab looks like the regular chat.

![chat](https://cloud.githubusercontent.com/assets/15799098/15624756/55956562-2491-11e6-86ca-ebc2bdee9e32.png)

once you switch the channel or map everything works as intended, so it's not a big deal!
