### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by maxchaoz** [Miei/TOS-lua#18]
Hi, my game crashed today and this is the result from the dump:

```
CreateOrGetControlSet at [C](-1)
(null) at [string "local addonName = "CLASSICCHAT";..."](343)
```
As ClassicChat is mentioned, I'm reporting the error here.
I'm using your latest release, if I can give any other info, feel free to ask.

Thanks!

**Comment by bruno-schmidt** [comment]
I experienced this error too, two or three times. Installed the addon through addon manager today, v 1.1.2.
