### ISSUE TITLE
Not working with contextmenuaddons for shouts

### ISSUE THREAD

**Issue by rpzky8** [Miei/TOS-lua#25]
Hi, just leaving a comment about this. For shouts, when I right click on the chat, it doesn't show any context menu. Works with normal chat though. Thanks.

**Comment by Miei** [comment]
Works fine for me. Are you sure that it's all shout messages or just the ones with links in them?

If it's messages with links in them, see https://github.com/Miei/TOS-lua/issues/17

**Comment by rpzky8** [comment]
Oh gotcha. Didn't notice that. Thanks!
