### ISSUE TITLE
Now Playing stops working/refreshing after warp or map change

### ISSUE THREAD

**Issue by Tesynia** [Miei/TOS-lua#26]
When i start the game everything is fine. It shows in the chat what bgm is now playing but when i change the map (via a statue, a scroll, or portal) this addon gets stuck. It stops showing the name of the current theme and if i type /np it only shows the last theme of the previous map.
But if i restart the game everything works fine until i switch the map again.

P.S.: I installed this addon via the Addon Manager

**Comment by juliuscgs** [comment]
Can confirm this, after changing location the addon stops working. Sometimes it is even removed from above the chat window and stays next to character HP/SP HUD. And when it does this, it does not show the name of bgm being played.

**Comment by redmagejoe** [comment]
Bump, this issue still exists.

**Comment by iAmSunwei** [comment]
bump again this is still an issue

**Comment by Miei** [comment]
I'm no longer playing ToS, I'd advise you to either uninstall the addon or update it yourself. I have removed it from the addon manager list.
