### ISSUE TITLE
Why LKchat cant use with Classic Chat together?

### ISSUE THREAD

**Issue by l3oytoys** [Miei/TOS-lua#27]
![screenshot_20160612_00001](https://cloud.githubusercontent.com/assets/8251906/15992572/81b3967c-30f9-11e6-9abc-0edc175d70ee.jpg)

**Comment by Miei** [comment]
They use the same hooks. They aren't compatible at the moment, as described in the addon description.

**Comment by l3oytoys** [comment]
okay thanks for answer me
