### ISSUE TITLE
cwcleric appear at each map change

### ISSUE THREAD

**Issue by vincentraulic** [Miei/TOS-lua#3]
Can you make a way to don't ask at each map change again until the situation change (join pt or leave one)

**Comment by Miei** [comment]
[not me](https://github.com/fiote/treeofsavior-addons).

**Comment by iBaer** [comment]
@Miei: It does for me as well.

Seems to be the case, that when you are in a party outside of a dungeon somehow.

**Comment by Miei** [comment]
Okay but that isn't my addon.

**Comment by fiote** [comment]
@vincentraulic and @iBaer yeah I need to check that out. I'm a cleric myself and bother me as well.

**Comment by iBaer** [comment]
@Miei: Totally misunderstood your "not me" and went with the flow so OP made me think this was the github for the cw mods (fiote's mods).
Sorry for the bother.
