### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by brokeandlazy** [Miei/TOS-lua#32]
The game stutters with each new message.

**Comment by Miei** [comment]
Are you using the latest version?

**Comment by brokeandlazy** [comment]
Did you release a new version since yesterday?  Just asking because I uninstalled it yesterday.

I was using the latest version as of Tuesday.

[https://www.reddit.com/r/treeofsavior/comments/4p2jsn/latest_version_of_classic_chat_seems_to_cause/](url)

**Comment by Miei** [comment]
Well, 2.0.6 should have fixed this issue already, as you can see in that reddit post. Were you using 2.0.6?

**Comment by brokeandlazy** [comment]
I'll try it again and see if it's fixed.  Thanks for the super quick replies.
