### ISSUE TITLE
Issues with Addon Manager

### ISSUE THREAD

**Issue by Zekrez** [Miei/TOS-lua#39]
Since last patch the chat stopped working, so I removed the game and downloaded again. The chat came back, but when I try to use the manager to reinstall the addons, it shows that I already have it downloaded, but I don't. I try to click "Uninstall" button, but nothing happens. I tried to delete data and addons folders and download again, but the error stillls. It recognizes that I had the addons before, but can't rescan to see if I still have. So I cannot download the addons again.

**Comment by Excrulon** [comment]
Read the FAQ for addon manager. Delete addons.json.

https://github.com/Excrulon/Tree-of-Savior-Addon-Manager/blob/master/README.md
