### ISSUE TITLE
cabinetCommas not working in the Retrieve tab

### ISSUE THREAD

**Issue by Nyuha** [Miei/TOS-lua#7]
Not a big problem, but still.

![432555](https://cloud.githubusercontent.com/assets/13547660/15270640/0d30776a-19fd-11e6-801e-49713cc911fd.png)

Great addons, keep it up!

**Comment by TehSeph** [comment]
https://github.com/Miei/TOS-lua/blob/master/addons/cabinetcommas/cabinetcommas.lua#L4
`local frame = ui.GetFrame("market_sell");` should be `local frame = ui.GetFrame("market_cabinet");`
Simple fix. :)

**Comment by Miei** [comment]
Yup, typo. Again didn't test this one because I had nothing in that tab.
